name: lazy_log
description: Simple [log] with global [enableLog] to turn on and off and [forced] to override individually.

version: 2.0.1
homepage: https://github.com/j-siu/flutter_lazy

environment:
  sdk: '>=3.0.2 <4.0.0'

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.3
