name: lazy_log
description: Simple [log] with global [enableLog] to turn on and off and [forced] to override individually.

version: 2.0.2
homepage: https://github.com/j-siu/flutter_lazy

environment:
  sdk: ^3.9.2

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
