name: lazy_ui_utils
description: A collection of flutter UI utilities, widgets, helper functions and handy defaults.
version: 1.0.0
homepage: https://github.com/j-siu/flutter_lazy

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_switch: ^0.3.2
  theme_provider: ^0.6.0
  lazy_extensions: ^2.1.0
  lazy_log: ^2.0.0
  universal_html: ^2.2.3
  url_launcher: ^6.1.11
  # lazy_extensions:
  #   path: ../lazy_extensions
  # lazy_log:
  #   path: ../lazy_log

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
