name: lazy_sign_in_google
description: '[google_sign_in] wrapper using [lazy_sign_in] interface. Support web and app Google sign in.'

version: 2.1.3
homepage: https://github.com/j-siu/flutter_lazy

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  google_sign_in: ^7.2.0
  http: ^1.5.0
  lazy_log: ^2.0.2
  lazy_sign_in: ^2.1.2
  # lazy_log:
  #   path: ../lazy_log
  # lazy_sign_in:
  #   path: ../lazy_sign_in

dev_dependencies:
  flutter_lints: ^6.0.0
  test: ^1.26.3
